// <auto-generated />
namespace TidrAppProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_employees_in_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_employees_in_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201901310946258_added_employees_in_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
