// <auto-generated />
namespace TidrAppProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_field_for_userID_in_employees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_field_for_userID_in_employees));
        
        string IMigrationMetadata.Id
        {
            get { return "201901310912407_added_field_for_userID_in_employees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
